lib/fracomex_web/router.ex
defmodule FracomexWeb.Router do
  use FracomexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {FracomexWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FracomexWeb do
    pipe_through :browser

    get "/", PageController, :index

    # Route pour la recherche
    post "/search", PageController, :search

    post "/send_contact_mail", PageController, :send_contact_mail
    live "/search", Live.ProductLive, :search

    post "/add_to_cart", PageController, :add_to_cart
    get "/add_to_cart", PageController, :add_to_cart

    get "/contact", PageController, :contact
    get "/validation-panier", PageController, :validate_cart
    # get "/boutique", ProductController, :index
    live "/boutique", Live.ProductLive, :index

    # get "/product-details", SingleProductController, :index
    live "/boutique/:categorie/:sous_categorie/:nom_produit/:id_produit", Live.ProductLive, :product_details

    live "/boutique/vide", Live.ProductLive, :empty_items

    live "/boutique/:categorie/", Live.ProductLive, :family
    live "/boutique/:categorie/:sous_categorie", Live.ProductLive, :sub_family

    # get "/panier", CartController, :index
    live "/panier", Live.CartLive, :index

    # get "/users", UsersController, :index
    get "/connexion", UsersController, :signin
    get "/inscription", UsersController, :signup
    get "/deconnexion", UsersController, :signout
    get "/verification-confirmation-mail", UsersController, :check_signup_mail
    get "/verification-mdp-oublie", UsersController, :check_forgotten_password_mail
    get "/mdp-oublie", UsersController, :forgot_password
    get "/renvoi-verification-mail", UsersController, :resend_confirmation_mail
    get "/mon-profil", UsersController, :my_account
    get "/mon-adresse", UsersController, :my_address
    get "/mes-commandes", UsersController, :my_orders

    post "/valider-connexion", UsersController, :submit_signin
    post "/valider-inscription", UsersController, :submit_signup
    post "/valider-commande", PageController, :submit_order
    post "/recap-commande", PageController, :recap_order
    post "/envoi-mail-mdp-oublie", UsersController, :submit_forgotten_password
    post "/renvoi-mail-confirmation", UsersController, :submit_resend_confirmation_mail

    put "/modifier-motdepasse/:id", UsersController, :submit_new_password_forgotten
    put "/modifier-profil/:id", UsersController, :edit_my_account
    put "/modifier-adresse/:id", UsersController, :edit_my_address
  end

  # Other scopes may use custom stacks.
  # scope "/api", FracomexWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: FracomexWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/fracomex_web/templates/page/arrivage.html.heex
  
		
		
		<!--all arrivals start -->
		<section id="new-arrivals" class="all-product">
			<div class="container">
				<div class="section-header">
				<h1 class="title-section">ARRIVAGES</h1>
			</div><!--/.section-header-->

			<div class="container" style="margin: 2rem 0 -2rem 0">
				<p class="all-alert alert animated fadeInRight alert-info" role="alert"><%= get_flash(@conn, :info_panier) %></p>
				<p class="all-alert alert animated fadeInRight alert-danger" role="alert"><%= get_flash(@conn, :error_panier) %></p>
			</div>

				<div class="all-product-content">
					<div class="row">
					<%= for item <- @items do %>
						<% family_caption = 
							cond do
								is_nil(item.family) ->
									"famille"
								true -> 
									"#{item.family.caption}"
							end
						%>

						<% sub_family_caption = 
							cond do 
								is_nil(item.sub_family) ->
									"sous-famille"
								true -> 
									"#{item.sub_family.caption}"
							end 
						%>
						<div class="col-md-3 col-sm-4">
							<div class={"details-product-#{item.id}"} id="details">
							<a href={Routes.product_path(@conn, :product_details, family_caption, sub_family_caption, "#{item.caption}", item.id)} class={"product-#{item.id}"} >
								<div class="single-product-bg shadow" id={"product-#{item.id}"} data-product-id={item.id}>
									<img src={Routes.static_path(@conn, "/images/big-items/#{item.image}")} alt={item.image}>
									<div class="single-product-bg-overlay"></div>
									<div class="sale bg-1" hidden>
										<p hidden><%= Enum.count(@items) %> news</p>
										<p>Arrivage</p>
									</div>
									<!--product_title-->
								<div class="product-name" id={"name-#{item.id}"}>	
								<a class="a-product-name" href="#"><%= String.capitalize(item.caption) %></a>
								</div>
								<!--product_price-->
								<div class="product-price" id={"price-#{item.id}"}>
								<p class="p-product-price"><%= Fracomex.Utilities.price_format(item.sale_price_vat_excluded) %> €</p>
								</div>

								<% real_stock = 
									item.real_stock 
									|> Decimal.to_float()
									|> trunc() 
								%>

								<%= if real_stock > 0 do %>
									<div class="new-arrival-cart">

										<form action={:add_to_cart} method="post">
											<input type="hidden" name="_csrf_token" value={Plug.CSRFProtection.get_csrf_token()}>
											<input type="hidden" name="id" value={item.id}>
											<p class="add-to-cart">
												<span class="lnr lnr-cart"></span>
												<button type="submit" class="addtocart">Ajouter au panier</button>
											</p>
										</form>

										
										<!--p class="arrival-review pull-right">
											<span class="lnr lnr-heart"></span>
											<span class="lnr lnr-frame-expand" title="Zoom"></span>
										</p-->
									</div>
								<!--ne plus afficher rupture de stock-->	
								<% else %>
									<div class="out-of-stock-ribbon" style="display: none;">
										<p style="font-size: 1rem;"></p>
									</div>
								<% end %>
									
								</div>
							</a>	
							</div>
							
						</div>
					<% end %>
					</div>
				</div>
			</div><!--/.container-->
		
		</section><!--/.new-arrivals-->
		<!--all-arrivals end -->

lib/fracomex_web/templates/page/cart_validation.html.heex
<section class="top-section p-4">
            <div class="container px-4 px-lg-5 my-5" id="shop-banner">
                <div class="text-center">
                    <h1 class="">Validation de votre panier</h1>
                </div>
            </div>
</section>
<div class="container" style="margin-top: 5rem; margin-bottom: 5rem;">
    <div class="row">
		<div class="col-md-12">	
			 <table class="table align-middle checkout">
				<thead class="head-table">
					<tr>
					<th scope="col">Produits</th>
					<th scope="col" class="text-center">Quantité</th>
					<th scope="col" class="text-center">Total</th>
					</tr>
				</thead>
				<tbody>
				<%= for cart_item <- @cart_items do %>
					<tr class="validate-checkout">
						<td class="cart-validation-td">
							<div class="order-item-container">
								<img src={Routes.static_path(@conn, "/images/big-items/#{cart_item[:item].image}")} alt="" width="50" height="50">
								<p><%= String.capitalize(cart_item[:item].caption) %></p>
							</div>
						</td>
						<td class="item-qty cart-validation-td"><%= cart_item[:quantity] %></td>
						<td class="item-price cart-validation-td"><%= Fracomex.Utilities.price_format(cart_item[:item].sale_price_vat_excluded) %> €</td>
					</tr>
				<% end %>
				</tbody>
				<tfoot class="foot-table">
					<tr class="text-offset">
					<td colspan="2" class="label-subtotal">Sous-total :</td>
					<td class="subtotal"><%= Fracomex.Utilities.price_format(Decimal.new("148.90")) %> €</td>
					</tr>
					<tr class="text-offset">
					<td colspan="2" class="label-payement">Moyen de paiement :</td>
					<td class="mod-payement">E-transactions payement</td>
					</tr>
					<tr class="text-offset">
					<td colspan="2" class="label-total">Total :</td>
					<td class="total"><%= Fracomex.Utilities.price_format(Decimal.new("148.90")) %> €</td>
					</tr>
				</tfoot>
			</table>
		</div> 
	</div>
	<div class="row">
		<div class="col-md-12 mb-4">	
			<h5 class="link-info">Vos données personnelles seront utilisées pour le traitement de votre commande, vous accompagner au cours de votre visite du site web, et pour d'autres raisons décrites dans notre <a href="/" class="link-pc">politique de confidentialité</a></h5>
		</div> 
		<h5 class="link-cgv"><input type="checkbox" class="text-start" style="width: 4%;"/>J'ai lu et j'accepte les <a href="/" class="link-to-cgv">condition générales</a></h5>
		<button class="button-cart validate-cart">
				<a href="/validation-commande" class="validate-cart"><span class="single_product_addtocart">Passer à la commande</span></a>
		</button>
	</div>
</div>

lib/fracomex_web/templates/page/contact.html.heex
<section class="top-section p-4">
            <div class="container px-4 px-lg-5 my-5" id="shop-banner">
                <div class="text-center">
                    <h1 class="">Contact</h1>
					
                </div>
            </div>
</section>
<div class="container" style="margin-top: 5rem; margin-bottom: 5rem;">
    <div class="row">
		<div class="col-md-5">	
			<div class="form-contact">	
				<%= form_for nil, Routes.page_path(@conn, :send_contact_mail), fn f -> %>
					<label for="name">Nom</label>	
					<input type="text" name="name" class="form-control mb-4">

					<label for="mail">E-mail</label>	
					<input type="text" name="mail" class="form-control mb-4">

					<label for="subject">Objet</label>	
					<input type="text" name="subject" class="form-control mb-4">
					
					<label for="message">Messages</label>	
					<textarea type="textarea" name="message" class="form-control mb-4" style="min-height: 200px"></textarea>
					
					<div class="row mb-4 text-center">
						<button class="btn-cart valide-cart">
							<input class="single_product_addtocart" type="submit" value="Envoyer">
						</button>
					</div>
				<% end %>
			</div> 
		</div>
		<div class="col-md-7">	
			<div class="row info mb-4">
				<div class="col-md-4 phone">		
				<div class="">
					<h2 class="mb-4">
					<span class="lnr lnr-phone-handset primary-color" style="font-size: 40px;"></span>
					</h2>
					<h4 class="mb-4">
					TELEPHONE 
					</h4>
					<h5 class="mb-4">
					0269 61 25 38
					</h5>
				</div>	
				</div>
				<div class="col-md-4 mail">		
				<div class="">
					<h2 class="mb-4">
					<span class="lnr lnr-envelope primary-color" style="font-size: 40px;"></span>
					</h2>
					<h4 class="mb-4">
					E-MAIL
					</h4>
					<h5 class="mb-4">
					<a href="mailto:devis.fracomex@gmail.com" style="font-size: 14px;">devis.fracomex@gmail.com</a>
					</h5>
				</div>	
				</div>
				<div class="col-md-4 location">		
				<div class="">
					<h2 class="mb-4">
					<span class="lnr lnr-map-marker primary-color" style="font-size: 40px;"></span>
					</h2>
					<h4 class="mb-4">
					ADRESSE
					</h4>
					<h5 class="mb-4">
					 BP 512 Avenue de l'Europe ZI Kawéni- Mamoudzou
					</h5>
				</div>	
				</div>
			</div> 
			<div class="row">
				<div class="col-md-12">
					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3891.105946017057!2d45.223340415354656!3d-12.771631159285759!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x220a133a757efc9f%3A0x8309d255c0da6ea2!2sFRACOMEX%20sarl!5e0!3m2!1sen!2smg!4v1660023588391!5m2!1sen!2smg" width="665" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
				</div>
			</div>
		</div>   
	</div>
</div>

lib/fracomex_web/templates/page/contact_breadcrumb.html.heex
<% selected_link = "pointer-events: none;font-weight: lighter;" %>
    <ul class="breadcrumb-link">
        <li class="breadcrumb-item-link"><a href="/">Accueil / </a> </li>
        <li class="breadcrumb-item-link" aria-current="page"> <a href={Routes.page_path(@conn, :contact)} style={if (@conn.request_path=="/contact" or @conn.request_path=="/contact"), do: selected_link, else: ""}> Contact</a></li>
        <!--li class="breadcrumb-item"><a href={Routes.users_path(@conn, :my_account)} style={if (@conn.request_path=="/mon-profil" or @conn.request_path=="/modifier-profil/#{@user.id}"), do: selected_link, else: ""}>Mon profil</a></li-->
    </ul>

lib/fracomex_web/templates/page/order_validation.html.heex
<section class="top-section p-4">
            <div class="container px-4 px-lg-5 my-5" id="shop-banner">
                <div class="text-center">
                    <h1 class="">Validation de votre commande</h1>
                </div>
            </div>
</section>
<div class="container" style="margin-top: 5rem; margin-bottom: 5rem;">
    <div class="row">
		<div class="col-md-12">	
			 <table class="table align-middle checkout">
				<thead class="head-table">
					<tr>
					<th scope="col" style="color: white;">Produits</th>
					<th scope="col" style="color: white;" class="text-center">Prix unitaire</th>
					<th scope="col" style="color: white;" class="text-center">Quantité</th>
					<th scope="col" style="color: white;" class="text-center">Total</th>
					</tr>
				</thead>
				<tbody>
				<%= for order_line <- @order.order_lines do %>
					<tr class="validate-checkout">
						<td class="cart-validation-td">
							<div class="order-item-container">
								<img src={Routes.static_path(@conn, "/images/big-items/#{order_line.item.image}")} alt="" width="50" height="50">
								<p class="order-item-caption"><%= String.capitalize(order_line.item.caption) %></p>
							</div>
						</td>
						<td class="item-qty cart-validation-td"><%= Fracomex.Utilities.price_format(order_line.item.sale_price_vat_excluded) %> €</td>
						<td class="item-qty cart-validation-td"><%= order_line.quantity %></td>
						<td class="item-price cart-validation-td"><%= Fracomex.Utilities.price_format(Decimal.mult order_line.quantity, order_line.item.sale_price_vat_excluded) %> €</td>
					</tr>
				<% end %>
				</tbody>
				<tfoot class="foot-table">
					<tr class="text-offset">
                        <td colspan="3" class="label-subtotal">Sous-total :</td>
                        <td class="subtotal"><%= @order.sum |> Fracomex.Utilities.price_format() %> €</td>
					</tr>
					<tr class="text-offset">
                        <td colspan="3" class="label-payement">Moyen de paiement :</td>
                        <td class="mod-payement">E-transactions payement</td>
					</tr>
					<tr class="text-offset">
                        <td colspan="3" class="label-total">Total :</td>
                        <td class="total"><%= @order.sum |> Fracomex.Utilities.price_format() %> €</td>
					</tr>
				</tfoot>
			</table>
		</div> 
	</div>
	<div class="row">
		<div class="col-md-12 mb-4">	
			<h5 class="link-info">Vos données personnelles seront utilisées pour le traitement de votre commande, vous accompagner au cours de votre visite du site web, et pour d'autres raisons décrites dans notre <a href="/" class="link-pc">politique de confidentialité</a></h5>
		</div> 
        <%= form_for nil, "/recap-commande", fn f -> %>
			<h5 class="link-cgv">
			<!-- <input type="checkbox" class="text-start" style="width: 4%;" value="false"/>J'ai lu et j'accepte les <a href="/" class="link-to-cgv">condition générales</a></h5> -->
			<%= checkbox f, :cvg_accepted, class: "text-start", style: "width: 4%;" %> J'ai lu et j'accepte les <a href="/" class="link-to-cgv">condition générales</a></h5>            
			<p style="color: red; font-weight: bold; font-size: 12px;"><%= @not_accepted_error_message %></p>
			<input type="hidden" name="order_id" value={@order.id}>
            <button style="" class="button-cart validate-cart">
            Passer à la commande
                <input style="display: none;" type="submit" class="single_product_addtocart" value="">
            </button>
        <% end %>
	</div>
</div>

lib/fracomex_web/templates/page/recap_order.html.heex
<section class="top-section p-4">
            <div class="container px-4 px-lg-5 my-5" id="shop-banner">
                <div class="text-center">
                    <h1 class="">Récapitulatif de votre commande</h1>
                </div>
            </div>
</section>
<div class="container" style="margin-top: 5rem; margin-bottom: 5rem;">
    <div class="row">
		<div class="col-md-12">	
			<table class="table align-middle checkout">
                        <thead class="head-table">
                            <tr>
                            <th scope="col" style="color: white;">Référence / Numéro de commande</th>
                            <th scope="col" class="text-center" style="color: white;">Date de validation de commande</th>
                            <th scope="col" class="text-center" style="color: white;">Total</th>
                            <th scope="col" class="text-center" style="color: white;">Moyen de paiement</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="">
                                <td class=""><p style="font-weight: bold;"><%= @order.id %></p></td>
                                <td class="">
                                    <p class="text-center"><%= @date %></p>
                                </td>
                                <td class=""><p class="text-center"><%= Fracomex.Utilities.price_format(@order.sum) %> €</p></td>
                                <td class=""><p class="text-center">E-transactions</p></td>
                                
                            </tr>
                        </tbody>
			        </table>
		</div> 
	</div>
 
            <button style="" class="button-cart validate-cart">
                <span type="submit" class="single_product_addtocart" value=""> Passer au paiement</span>
            </button>
</div>